In [13]:
import numpy as np

Theta = np.array([
    [24/24, 0, 0, 0, 0, 0, 0, 0, 0],
    [14/24, 1/24, 0, 1/24, 8/24, 0, 0, 0, 0],
    [10/24, 1/24, 0, 1/24, 0, 2/24, 0, 2/24, 8/24],
    [8/24, 1/24, 0, 1/24, 14/24, 0, 0, 0, 0],
    [0, 0, 0, 0, 24/24, 0, 0, 0, 0],
    [0, 0, 0, 0, 12/24, 2/24, 0, 2/24, 8/24],
    [8/24, 1/24, 0, 1/24, 0, 2/24, 0, 2/24, 10/24],
    [0, 0, 0, 0, 8/24, 2/24, 0, 2/24, 12/24],
    [0, 0, 0, 0, 0, 0, 0, 0, 24/24]
])

w = np.array([
    1257,
    143,
    600,
    357,
    3080.5,
    1562.5,
    900,
    937.5,
    1162.5
])

p1 = np.dot(np.diag(w),Theta)

In [20]:
row = p1[0]+p1[1]+p1[2]
np.round(row/np.sum(row),4)

array([0.7952, 0.0155, 0.    , 0.0155, 0.0238, 0.025 , 0.    , 0.025 ,
       0.1   ])

In [19]:
row = p1[3]+p1[4]+p1[5]
np.round(row/np.sum(row),4)

array([0.0238, 0.003 , 0.    , 0.003 , 0.814 , 0.026 , 0.    , 0.026 ,
       0.1042])

In [21]:
row = p1[6]+p1[7]+p1[8]
np.round(row/np.sum(row),4)

array([0.1   , 0.0125, 0.    , 0.0125, 0.1042, 0.051 , 0.    , 0.051 ,
       0.6688])