In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pickle
import pandas as pd
import os

In [5]:
A = np.array([
    [1,1,0],
    [1,0,1],
    [0,1,1]
])

b = np.array([2000,3000,4000])

np.linalg.inv(A)@b

array([ 500., 1500., 2500.])

In [3]:
pop_dict

{'CONGRESO DE TUCUMAN': 33627.720567000004,
 'JUAN MANUEL DE ROSAS VILLA URQUIZA': 22387.678335000004,
 'ECHEVERRIA': 14408.99769,
 'PLAZA DE LOS VIRREYES EVA PERON': 19537.22766,
 'RIO DE JANEIRO': 27289.444285999998,
 'AV. LA PLATA': 36604.60837,
 'JOSE MARIA MORENO': 24699.952982,
 'CASTRO BARROS': 22711.676878,
 'RETIRO': 11238.5265,
 'JURAMENTO': 20730.150928000003,
 'DE LOS INCAS PARQUE CHAS': 17504.073704000002,
 'SCALABRINI ORTIZ': 18594.056888,
 'FACULTAD DE DERECHO JULIETA LANTERI': 27783.881553,
 'SAN JOSE DE FLORES': 19365.418923999998,
 'VARELA': 13642.411734,
 'SAN PEDRITO': 32007.574021,
 'MEDALLA MILAGROSA': 21660.334872,
 'EMILIO MITRE': 20934.18406,
 'LORIA': 22880.608813,
 'PLAZA MISERERE': 12795.709134,
 'VENEZUELA': 25013.081131999996,
 'ALBERTI': 7807.551336,
 'SAN JOSE': 8228.887200000001,
 'CONSTITUCION': 20580.501846,
 'SAN JUAN': 14305.31085,
 'PASCO': 10554.652732,
 'HOSPITALES': 27412.922886999997,
 'BOEDO': 36424.012275999994,
 'INCLAN MEZQUITA AL AHMAD': 1

In [2]:
with open("Buenos Aires Home Patches.pkl", "rb") as file:
    home_patches = pickle.load(file)

with open("BA_Patch_Population_Map_1km.pkl", "rb") as file:
    pop_dict = pickle.load(file)
    
# Assuming pop_dict is a pandas DataFrame
pop_dict = dict(zip(pop_dict['estacion'], pop_dict['population']))
pop_dict = dict(sorted(pop_dict.items()))

with open("ba_big station list.pkl", "rb") as file:
    station_list = pickle.load(file)

# Load the cleaned CSV file
fixed_df = pd.read_csv("BA_Turnstile_Fixed.csv")

# Sum across all days to get total passengers per station for the year
annual_totals = fixed_df.groupby("ESTACION", as_index=False)["pax_TOTAL"].sum()

# Divide by 364 to get the average daily passenger count per station
annual_totals["pax_TOTAL"] = annual_totals["pax_TOTAL"] / 364
cleaned_df = annual_totals.copy()
cleaned_df["daily_trips"] = cleaned_df["pax_TOTAL"]/2

# Save the result to a new file
cleaned_df.to_csv("BA_Turnstile_Daily_Trips.csv", index=False)

# Display the first few rows
print(cleaned_df.head(100))



                   ESTACION     pax_TOTAL   daily_trips
0                9 DE JULIO  20084.931319  10042.465659
1                    ACOYTE   6979.390110   3489.695055
2                    AGUERO   7781.934066   3890.967033
3                   ALBERTI   3008.618132   1504.309066
4            ANGEL GALLARDO   9082.868132   4541.434066
..                      ...           ...           ...
73  TRIBUNALES TEATRO COLON   7634.859890   3817.429945
74   TRONADOR VILLA ORTUZAR   3652.038462   1826.019231
75                  URUGUAY   8166.043956   4083.021978
76                   VARELA   1524.623626    762.311813
77                VENEZUELA   5000.445055   2500.222527

[78 rows x 3 columns]


In [5]:
b_array = np.array(list(cleaned_df['daily_trips']))
b_array

array([10042.46565934,  3489.69505495,  3890.96703297,  1504.30906593,
        4541.43406593,  4001.72115385,  1755.80631868,  1263.83791209,
        1651.6717033 ,  3663.49313187,  4567.4739011 ,  4869.89835165,
        3289.59615385,  5488.25961538,  2145.90934066,  2398.63324176,
        1497.02197802, 13324.69230769,  4120.73763736, 10399.32692308,
       27453.80769231,  2298.78708791,  5593.81181319,  2919.32554945,
        3326.34340659,  1908.75549451,  1434.1978022 ,  1301.5206044 ,
        8836.88873626,  2236.23214286,  5639.3228022 ,  4217.14010989,
        1337.24725275,  1312.42032967,  4630.4010989 ,  1850.88324176,
        5557.60576923,  3651.75137363,  1434.44917582,  8691.07142857,
        2893.29945055,  6122.00274725,  3143.3489011 ,  2312.24313187,
        8221.89010989,  2773.05631868,  5626.39285714,   649.40384615,
        5291.6717033 ,  1633.90796703,  4173.28846154,  3971.15796703,
        6725.23626374,  3382.5260989 ,   926.99175824,  3457.1510989 ,
      

In [6]:
pop_dict

{'9 DE JULIO': 3885.8633999999997,
 'ACOYTE': 23085.92196,
 'AGUERO': 18317.850967,
 'ALBERTI': 7807.551336,
 'ANGEL GALLARDO': 28498.772215999998,
 'AV. DE MAYO': 2514.3822,
 'AV. LA PLATA': 36604.60837,
 'BELGRANO': 10952.801249999999,
 'BOEDO': 36424.012275999994,
 'BULNES': 17483.918429,
 'CALLAO': 21922.347559,
 'CALLAO - MAESTRO ALFREDO BRAVO': 7279.353745,
 'CARABOBO': 21958.021048,
 'CARLOS GARDEL': 21621.491481999998,
 'CASEROS': 14425.98459,
 'CASTRO BARROS': 22711.676878,
 'CATALINAS': 7162.1795999999995,
 'CATEDRAL': 4247.78205,
 'CONGRESO': 12738.784285999998,
 'CONGRESO DE TUCUMAN': 33627.720567000004,
 'CONSTITUCION': 20580.501846,
 'CORDOBA': 14958.342735,
 'CORRIENTES': 11205.282009999999,
 'DE LOS INCAS PARQUE CHAS': 17504.073704000002,
 'DORREGO': 19480.309064,
 'ECHEVERRIA': 14408.99769,
 'EMILIO MITRE': 20934.18406,
 'ENTRE RIOS RODOLFO WALSH': 19506.513332000002,
 'F. LACROZE': 16699.992156,
 'FACULTAD DE DERECHO JULIETA LANTERI': 27783.881553,
 'FACULTAD DE MEDIC

In [3]:
import numpy as np

# Example: 4 stations with total trips recorded
stations = ["A", "B", "C", "D"]
total_trips = np.array([2150, 3050, 2200, 2800])  # Hypothetical total trips per station

# Generate variable mappings for bidirectional flows
station_pairs = [(i, j) for i in range(len(stations)) for j in range(i + 1, len(stations))]
num_vars = len(station_pairs)

# Construct matrix A (each row represents a station, each column a bidirectional trip)
A = np.zeros((len(stations), num_vars))

for station_idx, station in enumerate(stations):
    for var_idx, (i, j) in enumerate(station_pairs):
        if station_idx in (i, j):
            A[station_idx, var_idx] = 1  # This trip contributes to the station's total count

# Solve using least squares
X, residuals, rank, s = np.linalg.lstsq(A, total_trips, rcond=None)

# Compute error: how wrong is the estimation?
estimated_trips = A @ X
error = total_trips - estimated_trips  # Difference between actual and estimated totals
error_norm = np.linalg.norm(error)

# Display results
print("Station Pair Flow Estimates:")
for (i, j), flow in zip(station_pairs, X):
    print(f"{stations[i]} <-> {stations[j]}: {flow:.2f}")

print("\nResidual Errors (Actual - Estimated):")
for station, err in zip(stations, error):
    print(f"{station}: {err:.2f}")

print(f"\nTotal Residual Error Norm: {error_norm:.2f}")


Station Pair Flow Estimates:
A <-> B: 900.00
A <-> C: 475.00
A <-> D: 775.00
B <-> C: 925.00
B <-> D: 1225.00
C <-> D: 800.00

Residual Errors (Actual - Estimated):
A: 0.00
B: 0.00
C: 0.00
D: 0.00

Total Residual Error Norm: 0.00


In [8]:
b_array

array([10042.46565934,  3489.69505495,  3890.96703297,  1504.30906593,
        4541.43406593,  4001.72115385,  1755.80631868,  1263.83791209,
        1651.6717033 ,  3663.49313187,  4567.4739011 ,  4869.89835165,
        3289.59615385,  5488.25961538,  2145.90934066,  2398.63324176,
        1497.02197802, 13324.69230769,  4120.73763736, 10399.32692308,
       27453.80769231,  2298.78708791,  5593.81181319,  2919.32554945,
        3326.34340659,  1908.75549451,  1434.1978022 ,  1301.5206044 ,
        8836.88873626,  2236.23214286,  5639.3228022 ,  4217.14010989,
        1337.24725275,  1312.42032967,  4630.4010989 ,  1850.88324176,
        5557.60576923,  3651.75137363,  1434.44917582,  8691.07142857,
        2893.29945055,  6122.00274725,  3143.3489011 ,  2312.24313187,
        8221.89010989,  2773.05631868,  5626.39285714,   649.40384615,
        5291.6717033 ,  1633.90796703,  4173.28846154,  3971.15796703,
        6725.23626374,  3382.5260989 ,   926.99175824,  3457.1510989 ,
      

In [9]:
len(station_pairs)

6

In [6]:
import numpy as np
from scipy.optimize import minimize

# Generate unique station pairs for bidirectional flows
num_stations = len(station_list)
station_pairs = [(i, j) for i in range(num_stations) for j in range(i + 1, num_stations)]
num_vars = len(station_pairs)

# Construct matrix A dynamically
A = np.zeros((num_stations, num_vars))

for station_idx in range(num_stations):
    for var_idx, (i, j) in enumerate(station_pairs):
        if station_idx in (i, j):
            A[station_idx, var_idx] = 1  # This trip contributes to the station's total count

# Define objective function for quadratic optimization
def objective(X):
    return np.linalg.norm(A @ X - b_array) ** 2  # Minimize squared error

# Solve using constrained optimization (non-negative values)
X0 = np.ones(num_vars)  # Initial guess (small nonzero values to prevent collapse)
bounds = [(0, None) for _ in range(num_vars)]  # Non-negative constraints

res = minimize(objective, X0, bounds=bounds, method='L-BFGS-B')

X_opt = res.x  # Optimal trip flow values

# Compute final error
final_estimated_trips = A @ X_opt
final_error = b_array - final_estimated_trips
final_error_norm = np.linalg.norm(final_error)

# Display results
print("Station Pair Flow Estimates:")
for (i, j), flow in zip(station_pairs, X_opt):
    print(f"{station_list[i]} <-> {station_list[j]}: {flow:.2f}")

print("\nResidual Errors (Actual - Estimated):")
for station, err in zip(station_list, final_error):
    print(f"{station}: {err:.2f}")

print(f"\nTotal Residual Error Norm: {final_error_norm:.2f}")


Station Pair Flow Estimates:
9 DE JULIO <-> ACOYTE: 34.49
9 DE JULIO <-> AGUERO: 35.51
9 DE JULIO <-> ALBERTI: 29.54
9 DE JULIO <-> ANGEL GALLARDO: 37.18
9 DE JULIO <-> AV. DE MAYO: 35.81
9 DE JULIO <-> AV. LA PLATA: 30.14
9 DE JULIO <-> BELGRANO: 29.00
9 DE JULIO <-> BOEDO: 29.90
9 DE JULIO <-> BULNES: 34.97
9 DE JULIO <-> CALLAO: 37.24
9 DE JULIO <-> CALLAO - MAESTRO ALFREDO BRAVO: 37.96
9 DE JULIO <-> CARABOBO: 33.96
9 DE JULIO <-> CARLOS GARDEL: 39.51
9 DE JULIO <-> CASEROS: 31.15
9 DE JULIO <-> CASTRO BARROS: 31.81
9 DE JULIO <-> CATALINAS: 29.54
9 DE JULIO <-> CATEDRAL: 59.15
9 DE JULIO <-> CONGRESO: 36.05
9 DE JULIO <-> CONGRESO DE TUCUMAN: 51.81
9 DE JULIO <-> CONSTITUCION: 94.55
9 DE JULIO <-> CORDOBA: 31.63
9 DE JULIO <-> CORRIENTES: 39.81
9 DE JULIO <-> DE LOS INCAS PARQUE CHAS: 33.18
9 DE JULIO <-> DORREGO: 34.14
9 DE JULIO <-> ECHEVERRIA: 30.49
9 DE JULIO <-> EMILIO MITRE: 29.36
9 DE JULIO <-> ENTRE RIOS RODOLFO WALSH: 29.06
9 DE JULIO <-> F. LACROZE: 47.99
9 DE JULIO <-> 

In [6]:
len(station_pairs)

3003

In [7]:
x_ridge

NameError: name 'x_ridge' is not defined

In [19]:
b_array.shape

(78,)

In [20]:
A.shape

(78, 3003)

In [7]:
import numpy as np
from scipy.optimize import lsq_linear

# Regularization parameter (adjust as needed)
# lambda_reg = 1e-3  

# Compute the regularized least-squares solution
# AtA = A.T @ A
# Atb = A.T @ b_array
# I = np.eye(A.shape[1])

# Solve the regularized system
# x_ridge = np.linalg.solve(AtA + lambda_reg * I, Atb)

# Ensure non-negativity using constrained optimization
x_optimal = lsq_linear(A, b_array, bounds=(0, np.inf)).x

print(x_optimal)


[1.32628079e+02 1.32685694e+02 8.15846538e+01 ... 2.99571024e-01
 2.85014939e+01 8.43415380e-02]


In [43]:
len(x_optimal)

3003

In [72]:
np.sum(np.dot(A,x_optimal))

np.float64(334083.8002968955)

In [49]:
np.sum(b_array)

np.float64(334100.6758241758)

In [60]:
np.set_printoptions(suppress=True)


In [9]:
np.round((np.dot(A,x_optimal)-b_array)/np.dot(A,x_optimal),4)

array([-0.0001, -0.0001, -0.0001,  0.0004, -0.0001, -0.0001,  0.0003,
        0.0006,  0.0003, -0.0001, -0.0001, -0.0001, -0.    , -0.0001,
        0.0002,  0.0001,  0.0004, -0.0001, -0.0001, -0.0001, -0.0001,
        0.0001, -0.0001,  0.0001, -0.    ,  0.0002,  0.0005,  0.0006,
       -0.0001,  0.0001, -0.0001, -0.0001,  0.0005,  0.0006, -0.0001,
        0.0002, -0.0001, -0.0002,  0.0005, -0.0001,  0.0001, -0.0001,
        0.    ,  0.0001, -0.0001,  0.0001, -0.0001,  0.0004, -0.0001,
        0.0003, -0.0001, -0.0001, -0.0001, -0.0001, -0.0005, -0.0001,
        0.0007,  0.0002,  0.    , -0.0001, -0.0001, -0.0001, -0.0001,
        0.0001, -0.0001, -0.0001,  0.0001,  0.001 , -0.0001,  0.0003,
       -0.0001, -0.0001, -0.0001, -0.0001,  0.0003, -0.0001, -0.0022,
        0.0001])

In [10]:
np.dot(A,x_optimal)

array([10041.32253352,  3489.45297936,  3890.5298191 ,  1504.89584389,
        4540.94437024,  4001.3693086 ,  1756.31864986,  1264.59941594,
        1652.18634014,  3663.02515745,  4566.97975063,  4869.33091868,
        3289.51797725,  5487.53718951,  2146.25026416,  2398.87001876,
        1497.61335876, 13323.50203396,  4120.38668034, 10398.13482329,
       27452.1615894 ,  2299.08544156,  5593.06915977,  2919.50450961,
        3326.23491385,  1909.19052411,  1434.86174067,  1302.25663139,
        8835.77977988,  2236.54660107,  5638.57775028,  4216.75639077,
        1337.95109456,  1313.14546636,  4629.89707778,  1851.32853525,
        5556.86599038,  3651.19849783,  1435.10847154,  8689.96677066,
        2893.48425103,  6121.17820968,  3143.38271832,  2312.54316972,
        8220.80684098,  2773.26384707,  5625.64963795,   649.65039306,
        5291.00022628,  1634.41660822,  4172.92259984,  3970.79754604,
        6724.32570446,  3382.35445706,   926.56107928,  3456.93016381,
      

In [11]:
np.dot(A,x_optimal)

array([10041.32253352,  3489.45297936,  3890.5298191 ,  1504.89584389,
        4540.94437024,  4001.3693086 ,  1756.31864986,  1264.59941594,
        1652.18634014,  3663.02515745,  4566.97975063,  4869.33091868,
        3289.51797725,  5487.53718951,  2146.25026416,  2398.87001876,
        1497.61335876, 13323.50203396,  4120.38668034, 10398.13482329,
       27452.1615894 ,  2299.08544156,  5593.06915977,  2919.50450961,
        3326.23491385,  1909.19052411,  1434.86174067,  1302.25663139,
        8835.77977988,  2236.54660107,  5638.57775028,  4216.75639077,
        1337.95109456,  1313.14546636,  4629.89707778,  1851.32853525,
        5556.86599038,  3651.19849783,  1435.10847154,  8689.96677066,
        2893.48425103,  6121.17820968,  3143.38271832,  2312.54316972,
        8220.80684098,  2773.26384707,  5625.64963795,   649.65039306,
        5291.00022628,  1634.41660822,  4172.92259984,  3970.79754604,
        6724.32570446,  3382.35445706,   926.56107928,  3456.93016381,
      

In [12]:
b_array

array([10042.46565934,  3489.69505495,  3890.96703297,  1504.30906593,
        4541.43406593,  4001.72115385,  1755.80631868,  1263.83791209,
        1651.6717033 ,  3663.49313187,  4567.4739011 ,  4869.89835165,
        3289.59615385,  5488.25961538,  2145.90934066,  2398.63324176,
        1497.02197802, 13324.69230769,  4120.73763736, 10399.32692308,
       27453.80769231,  2298.78708791,  5593.81181319,  2919.32554945,
        3326.34340659,  1908.75549451,  1434.1978022 ,  1301.5206044 ,
        8836.88873626,  2236.23214286,  5639.3228022 ,  4217.14010989,
        1337.24725275,  1312.42032967,  4630.4010989 ,  1850.88324176,
        5557.60576923,  3651.75137363,  1434.44917582,  8691.07142857,
        2893.29945055,  6122.00274725,  3143.3489011 ,  2312.24313187,
        8221.89010989,  2773.05631868,  5626.39285714,   649.40384615,
        5291.6717033 ,  1633.90796703,  4173.28846154,  3971.15796703,
        6725.23626374,  3382.5260989 ,   926.99175824,  3457.1510989 ,
      

In [8]:
solution = x_optimal.copy()

In [78]:
len(x_optimal)

3003

In [79]:
station_pairs

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (0, 10),
 (0, 11),
 (0, 12),
 (0, 13),
 (0, 14),
 (0, 15),
 (0, 16),
 (0, 17),
 (0, 18),
 (0, 19),
 (0, 20),
 (0, 21),
 (0, 22),
 (0, 23),
 (0, 24),
 (0, 25),
 (0, 26),
 (0, 27),
 (0, 28),
 (0, 29),
 (0, 30),
 (0, 31),
 (0, 32),
 (0, 33),
 (0, 34),
 (0, 35),
 (0, 36),
 (0, 37),
 (0, 38),
 (0, 39),
 (0, 40),
 (0, 41),
 (0, 42),
 (0, 43),
 (0, 44),
 (0, 45),
 (0, 46),
 (0, 47),
 (0, 48),
 (0, 49),
 (0, 50),
 (0, 51),
 (0, 52),
 (0, 53),
 (0, 54),
 (0, 55),
 (0, 56),
 (0, 57),
 (0, 58),
 (0, 59),
 (0, 60),
 (0, 61),
 (0, 62),
 (0, 63),
 (0, 64),
 (0, 65),
 (0, 66),
 (0, 67),
 (0, 68),
 (0, 69),
 (0, 70),
 (0, 71),
 (0, 72),
 (0, 73),
 (0, 74),
 (0, 75),
 (0, 76),
 (0, 77),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (1, 10),
 (1, 11),
 (1, 12),
 (1, 13),
 (1, 14),
 (1, 15),
 (1, 16),
 (1, 17),
 (1, 18),
 (1, 19),
 (1, 20),
 (1, 21),
 (1, 22),
 (1, 23),
 (1, 24),
 (1, 25),
 (1, 26

In [82]:
pop_dict

{'CONGRESO DE TUCUMAN': 33627.720567000004,
 'JUAN MANUEL DE ROSAS VILLA URQUIZA': 22387.678335000004,
 'ECHEVERRIA': 14408.99769,
 'PLAZA DE LOS VIRREYES EVA PERON': 19537.22766,
 'RIO DE JANEIRO': 27289.444285999998,
 'AV. LA PLATA': 36604.60837,
 'JOSE MARIA MORENO': 24699.952982,
 'CASTRO BARROS': 22711.676878,
 'RETIRO': 11238.5265,
 'JURAMENTO': 20730.150928000003,
 'DE LOS INCAS PARQUE CHAS': 17504.073704000002,
 'SCALABRINI ORTIZ': 18594.056888,
 'FACULTAD DE DERECHO JULIETA LANTERI': 27783.881553,
 'SAN JOSE DE FLORES': 19365.418923999998,
 'VARELA': 13642.411734,
 'SAN PEDRITO': 32007.574021,
 'MEDALLA MILAGROSA': 21660.334872,
 'EMILIO MITRE': 20934.18406,
 'LORIA': 22880.608813,
 'PLAZA MISERERE': 12795.709134,
 'VENEZUELA': 25013.081131999996,
 'ALBERTI': 7807.551336,
 'SAN JOSE': 8228.887200000001,
 'CONSTITUCION': 20580.501846,
 'SAN JUAN': 14305.31085,
 'PASCO': 10554.652732,
 'HOSPITALES': 27412.922886999997,
 'BOEDO': 36424.012275999994,
 'INCLAN MEZQUITA AL AHMAD': 1

In [9]:
commuter_array = np.zeros([78,78])

for i in range(3003):
    joined_total = solution[i]
    
    station1_index = station_pairs[i][0]
    station2_index = station_pairs[i][1]
    
    station1 = station_list[station1_index]
    station2 = station_list[station2_index]
    
    station1_pop = pop_dict[station1]
    station2_pop = pop_dict[station2]
    total_pop = station1_pop + station2_pop
    
    commuter_array[station1_index][station2_index] = joined_total * station1_pop/total_pop
    commuter_array[station2_index][station1_index] = joined_total * station2_pop/total_pop
    
commuter_array

array([[0.00000000e+00, 1.91079156e+01, 2.32212717e+01, ...,
        6.48440107e+01, 1.05778153e+01, 1.45540792e+01],
       [1.13520164e+02, 0.00000000e+00, 2.33103116e+01, ...,
        3.76403072e+01, 5.94091595e-02, 8.43272977e+00],
       [1.09464423e+02, 1.84958961e+01, 0.00000000e+00, ...,
        4.08765550e+01, 1.07194878e-01, 1.08465629e+01],
       ...,
       [7.05655410e+01, 6.89471426e+00, 9.43648171e+00, ...,
        0.00000000e+00, 7.08855562e-02, 4.12167400e+00],
       [3.71363829e+01, 3.51072925e-02, 7.98345105e-02, ...,
        2.28685468e-01, 0.00000000e+00, 2.97660669e-02],
       [9.36837779e+01, 9.13667448e+00, 1.48110146e+01, ...,
        2.43798199e+01, 5.45754711e-02, 0.00000000e+00]])

In [10]:
np.sum(commuter_array)

np.float64(167041.90014844772)

In [11]:
# Taking the number of homebodies to be 0.13 as per the survey

full_commuter_array = commuter_array.copy()

homebody_pct = 0.13

for i in range(78):
    total_row_pop = np.sum(full_commuter_array[i])
    full_commuter_array[i][i] = homebody_pct*total_row_pop/(1-homebody_pct)
    
full_commuter_array

array([[3.28119505e+02, 1.91079156e+01, 2.32212717e+01, ...,
        6.48440107e+01, 1.05778153e+01, 1.45540792e+01],
       [1.13520164e+02, 3.12923898e+02, 2.33103116e+01, ...,
        3.76403072e+01, 5.94091595e-02, 8.43272977e+00],
       [1.09464423e+02, 1.84958961e+01, 3.17666075e+02, ...,
        4.08765550e+01, 1.07194878e-01, 1.08465629e+01],
       ...,
       [7.05655410e+01, 6.89471426e+00, 9.43648171e+00, ...,
        1.43864598e+02, 7.08855562e-02, 4.12167400e+00],
       [3.71363829e+01, 3.51072925e-02, 7.98345105e-02, ...,
        2.28685468e-01, 5.49947401e+01, 2.97660669e-02],
       [9.36837779e+01, 9.13667448e+00, 1.48110146e+01, ...,
        2.43798199e+01, 5.45754711e-02, 2.31203866e+02]])

In [21]:
# with open("Fixed Final Commuter Matrix Buenos Aires.pkl", "wb") as f:
    # pickle.dump(full_commuter_array, f)

In [16]:
with open("ba_travel_times.pkl", "rb") as file:
    travel_times = pickle.load(file)

with open("ba_new_paths.pkl", "rb") as file:
    paths = pickle.load(file)


In [17]:
home_patches = []

index = 0

for i in range(78):
    home_patches.append(index)
    index += 78+1

In [18]:
all_pairs = []

for i in range(78):
    for j in range(78):
        all_pairs.append((station_list[i],station_list[j]))
        
all_pairs

[('9 DE JULIO', '9 DE JULIO'),
 ('9 DE JULIO', 'ACOYTE'),
 ('9 DE JULIO', 'AGUERO'),
 ('9 DE JULIO', 'ALBERTI'),
 ('9 DE JULIO', 'ANGEL GALLARDO'),
 ('9 DE JULIO', 'AV. DE MAYO'),
 ('9 DE JULIO', 'AV. LA PLATA'),
 ('9 DE JULIO', 'BELGRANO'),
 ('9 DE JULIO', 'BOEDO'),
 ('9 DE JULIO', 'BULNES'),
 ('9 DE JULIO', 'CALLAO'),
 ('9 DE JULIO', 'CALLAO - MAESTRO ALFREDO BRAVO'),
 ('9 DE JULIO', 'CARABOBO'),
 ('9 DE JULIO', 'CARLOS GARDEL'),
 ('9 DE JULIO', 'CASEROS'),
 ('9 DE JULIO', 'CASTRO BARROS'),
 ('9 DE JULIO', 'CATALINAS'),
 ('9 DE JULIO', 'CATEDRAL'),
 ('9 DE JULIO', 'CONGRESO'),
 ('9 DE JULIO', 'CONGRESO DE TUCUMAN'),
 ('9 DE JULIO', 'CONSTITUCION'),
 ('9 DE JULIO', 'CORDOBA'),
 ('9 DE JULIO', 'CORRIENTES'),
 ('9 DE JULIO', 'DE LOS INCAS PARQUE CHAS'),
 ('9 DE JULIO', 'DORREGO'),
 ('9 DE JULIO', 'ECHEVERRIA'),
 ('9 DE JULIO', 'EMILIO MITRE'),
 ('9 DE JULIO', 'ENTRE RIOS RODOLFO WALSH'),
 ('9 DE JULIO', 'F. LACROZE'),
 ('9 DE JULIO', 'FACULTAD DE DERECHO JULIETA LANTERI'),
 ('9 DE JULIO

In [25]:
home_patches

[0,
 79,
 158,
 237,
 316,
 395,
 474,
 553,
 632,
 711,
 790,
 869,
 948,
 1027,
 1106,
 1185,
 1264,
 1343,
 1422,
 1501,
 1580,
 1659,
 1738,
 1817,
 1896,
 1975,
 2054,
 2133,
 2212,
 2291,
 2370,
 2449,
 2528,
 2607,
 2686,
 2765,
 2844,
 2923,
 3002,
 3081,
 3160,
 3239,
 3318,
 3397,
 3476,
 3555,
 3634,
 3713,
 3792,
 3871,
 3950,
 4029,
 4108,
 4187,
 4266,
 4345,
 4424,
 4503,
 4582,
 4661,
 4740,
 4819,
 4898,
 4977,
 5056,
 5135,
 5214,
 5293,
 5372,
 5451,
 5530,
 5609,
 5688,
 5767,
 5846,
 5925,
 6004,
 6083]

In [19]:
np.array(all_pairs)[np.array(home_patches)]

array([['9 DE JULIO', '9 DE JULIO'],
       ['ACOYTE', 'ACOYTE'],
       ['AGUERO', 'AGUERO'],
       ['ALBERTI', 'ALBERTI'],
       ['ANGEL GALLARDO', 'ANGEL GALLARDO'],
       ['AV. DE MAYO', 'AV. DE MAYO'],
       ['AV. LA PLATA', 'AV. LA PLATA'],
       ['BELGRANO', 'BELGRANO'],
       ['BOEDO', 'BOEDO'],
       ['BULNES', 'BULNES'],
       ['CALLAO', 'CALLAO'],
       ['CALLAO - MAESTRO ALFREDO BRAVO',
        'CALLAO - MAESTRO ALFREDO BRAVO'],
       ['CARABOBO', 'CARABOBO'],
       ['CARLOS GARDEL', 'CARLOS GARDEL'],
       ['CASEROS', 'CASEROS'],
       ['CASTRO BARROS', 'CASTRO BARROS'],
       ['CATALINAS', 'CATALINAS'],
       ['CATEDRAL', 'CATEDRAL'],
       ['CONGRESO', 'CONGRESO'],
       ['CONGRESO DE TUCUMAN', 'CONGRESO DE TUCUMAN'],
       ['CONSTITUCION', 'CONSTITUCION'],
       ['CORDOBA', 'CORDOBA'],
       ['CORRIENTES', 'CORRIENTES'],
       ['DE LOS INCAS PARQUE CHAS', 'DE LOS INCAS PARQUE CHAS'],
       ['DORREGO', 'DORREGO'],
       ['ECHEVERRIA', 'ECHEVERRIA']

In [102]:
# with open("Buenos Aires Home Patches.pkl", "wb") as f:
    # pickle.dump(home_patches, f)

In [20]:
flat_paths = paths.flatten()
flat_paths

array([None,
       list(['9 DE JULIO', 'AV. DE MAYO', 'SAENZ PENA', 'CONGRESO', 'PASCO', 'ALBERTI', 'PLAZA MISERERE', 'LORIA', 'CASTRO BARROS', 'RIO DE JANEIRO', 'ACOYTE']),
       list(['9 DE JULIO', 'TRIBUNALES TEATRO COLON', 'CALLAO', 'FACULTAD DE MEDICINA', 'SANTA FE CARLOS JAUREGUI', 'AGUERO']),
       ...,
       list(['VENEZUELA', 'PLAZA MISERERE', 'CORRIENTES', 'PASTEUR AMIA', 'CALLAO - MAESTRO ALFREDO BRAVO', 'URUGUAY']),
       list(['VENEZUELA', 'JUJUY', 'GRAL. URQUIZA', 'BOEDO', 'AV. LA PLATA', 'JOSE MARIA MORENO', 'EMILIO MITRE', 'MEDALLA MILAGROSA', 'VARELA']),
       None], dtype=object)

In [28]:
len(home_patches)

78

In [21]:
time_spent = np.zeros([6084,6084])

for i in range(6084):
    if i not in home_patches:
        pair = all_pairs[i]
        path = flat_paths[i]
        path_tuples = list(zip(path, path[1:]))

        
        work_patch = home_patches[station_list.index(pair[1])]
        # print(pair,"\n\n",path_tuples,"\n\n",work_patch)
        for leg in path_tuples:
            travel_time = travel_times[leg]
            travel_index = all_pairs.index(leg)
            time_spent[i][travel_index] = travel_time/60

In [22]:
time_spent_with_work = time_spent.copy()

for i in range(6084):
    work_patch = all_pairs[i][1]
    work_patch_idx = home_patches[station_list.index(work_patch)]
    time_spent_with_work[i][work_patch_idx] = 8

In [23]:
time_spent_with_work

array([[8., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 8.]])

In [24]:
for i in range(6084):
    print(np.sum(time_spent_with_work[i]))

8.0
8.250000000000004
8.133333333333335
8.100000000000003
8.183333333333334
8.016666666666667
8.266666666666667
8.05
8.25
8.15
8.05
8.033333333333335
8.350000000000001
8.116666666666667
8.233333333333334
8.183333333333335
8.083333333333334
8.033333333333333
8.066666666666666
8.4
8.133333333333335
8.100000000000001
8.083333333333334
8.333333333333332
8.25
8.366666666666667
8.333333333333334
8.150000000000002
8.266666666666667
8.166666666666666
8.066666666666666
8.033333333333333
8.066666666666666
8.216666666666669
8.3
8.200000000000001
8.066666666666668
8.333333333333334
8.3
8.400000000000002
8.183333333333335
8.366666666666667
8.133333333333333
8.033333333333333
8.05
8.15
8.200000000000001
8.350000000000001
8.150000000000002
8.05
8.266666666666667
8.3
8.233333333333334
8.26666666666667
8.083333333333334
8.066666666666668
8.166666666666668
8.033333333333333
8.4
8.05
8.200000000000001
8.116666666666667
8.283333333333333
8.316666666666666
8.083333333333334
8.216666666666667
8.033333333333

In [25]:
time_spent_all = time_spent_with_work.copy()

for i in range(6084):
    row_total = np.sum(time_spent_all[i])
    current_home_patch = all_pairs[i][0]
    home_idx = home_patches[station_list.index(current_home_patch)]
    time_spent_all[i][home_idx] += 24-row_total

In [26]:
time_spent_all

array([[24.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [15.75      ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [15.86666667,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , 15.86666667],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , 15.78333333],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , 24.        ]])

In [27]:
norm_time_spent_all = time_spent_all / time_spent_all.sum(axis=1, keepdims=True)
norm_time_spent_all

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.65625   , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.66111111, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.66111111],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.65763889],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [28]:
full_commuter_array

array([[3.28119505e+02, 1.91079156e+01, 2.32212717e+01, ...,
        6.48440107e+01, 1.05778153e+01, 1.45540792e+01],
       [1.13520164e+02, 3.12923898e+02, 2.33103116e+01, ...,
        3.76403072e+01, 5.94091595e-02, 8.43272977e+00],
       [1.09464423e+02, 1.84958961e+01, 3.17666075e+02, ...,
        4.08765550e+01, 1.07194878e-01, 1.08465629e+01],
       ...,
       [7.05655410e+01, 6.89471426e+00, 9.43648171e+00, ...,
        1.43864598e+02, 7.08855562e-02, 4.12167400e+00],
       [3.71363829e+01, 3.51072925e-02, 7.98345105e-02, ...,
        2.28685468e-01, 5.49947401e+01, 2.97660669e-02],
       [9.36837779e+01, 9.13667448e+00, 1.48110146e+01, ...,
        2.43798199e+01, 5.45754711e-02, 2.31203866e+02]])

In [29]:
flat_full_commuter_array = full_commuter_array.flatten()
flat_full_commuter_array,flat_full_commuter_array.shape

(array([3.28119505e+02, 1.91079156e+01, 2.32212717e+01, ...,
        2.43798199e+01, 5.45754711e-02, 2.31203866e+02]),
 (6084,))

In [30]:
norm_time_spent_all

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.65625   , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.66111111, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.66111111],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.65763889],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [31]:
product = norm_time_spent_all*flat_full_commuter_array[:,np.newaxis]

In [32]:
product,product.shape

(array([[3.28119505e+02, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [1.25395696e+01, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [1.53518407e+01, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        ...,
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 1.61177698e+01],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 3.58909522e-02],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 2.31203866e+02]]),
 (6084, 6084))

In [33]:
import numpy as np

# Define the number of rows per group
group_size = 78

# Determine the number of groups
num_groups = product.shape[0] // group_size

# Sum every 78 rows vertically
summed_rows = np.array([product[i * group_size:(i + 1) * group_size].sum(axis=0) for i in range(num_groups)])

# Initialize a new array of the same size
combined_times = np.zeros_like(product)

# Assign the summed values to the corresponding indices from home_patch
combined_times[home_patches[:num_groups]] = summed_rows


In [41]:
np.sum(commuter_array)

np.float64(167041.90014844772)

In [43]:
product

array([[3.28119505e+02, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.25395696e+01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.53518407e+01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.61177698e+01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 3.58909522e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 2.31203866e+02]])

In [34]:
arr = np.array([
    [0.5,0.1,0.4],
    [0.1,0.9,0.1],
    [0.2,0.2,0.6]
])

arr2 = np.array([10,100,1000])

(arr.T*arr2).T,arr*arr2[:,np.newaxis]

(array([[  5.,   1.,   4.],
        [ 10.,  90.,  10.],
        [200., 200., 600.]]),
 array([[  5.,   1.,   4.],
        [ 10.,  90.,  10.],
        [200., 200., 600.]]))

In [35]:
arr2,np.transpose(arr2),arr2[:,np.newaxis]

(array([  10,  100, 1000]),
 array([  10,  100, 1000]),
 array([[  10],
        [ 100],
        [1000]]))

In [42]:
total_first = np.zeros(6084)

for i in range(78):
    total_first += product[i]
    
total_first

array([1779.26520624,    0.        ,    0.        , ...,    0.        ,
          0.        ,    4.85135973])

In [43]:
np.sum(flat_full_commuter_array)

np.float64(192002.18407867555)

In [44]:
np.sum(product)

np.float64(192002.18407867532)

In [45]:
np.sum(combined_times)

np.float64(192002.18407867535)

In [46]:
import pickle
import scipy.sparse as sp


# Save dense version
# with open("Buenos Aires Expanded P Matrix.pkl", "wb") as f:
    # pickle.dump(product, f)

# Save sparse version
sparse_product = sp.csr_matrix(product)
# with open("Sparse Buenos Aires Expanded P Matrix.pkl", "wb") as f:
    # pickle.dump(sparse_product, f)

In [46]:
combined_times

array([[1779.26520624,    0.        ,    0.        , ...,    0.        ,
           0.        ,    4.85135973],
       [   0.        ,    0.        ,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       ...,
       [   0.        ,    0.        ,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       [  31.22792597,    0.        ,    0.        , ...,    0.        ,
           0.        , 1249.7848258 ]])

In [47]:
fixed_combined_times = combined_times.copy()

for i in range(6084):
    if i not in home_patches:
        fixed_combined_times[i][i] = 1
        

In [48]:
norm_p_matrix = fixed_combined_times / fixed_combined_times.sum(axis=1, keepdims=True)
norm_p_matrix

array([[0.70493974, 0.        , 0.        , ..., 0.        , 0.        ,
        0.00192209],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.01755866, 0.        , 0.        , ..., 0.        , 0.        ,
        0.70272193]])

In [49]:
from scipy.sparse import csr_matrix

sparse_norm_p_matrix = csr_matrix(norm_p_matrix)


In [50]:
# with open("Fixed Buenos Aires P-Matrix.pkl", "wb") as f:
    # pickle.dump(norm_p_matrix, f)

In [51]:
# with open("Fixed Sparse Buenos Aires P-Matrix.pkl", "wb") as f:
    # pickle.dump(sparse_norm_p_matrix, f)

In [203]:
flipped = norm_p_matrix.T
flipped

array([[0.70493974, 0.        , 0.        , ..., 0.        , 0.        ,
        0.01755866],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.00192209, 0.        , 0.        , ..., 0.        , 0.        ,
        0.70272193]])

In [204]:
np.sum(flipped[0])

np.float64(2.106976908520586)

In [206]:
flipped = norm_p_matrix.T
valid_patches = []
valid_patch_indices = []

for i in range(6084):
    if np.sum(flipped[i]) != 1:
        valid_patches.append([all_pairs[i][0],all_pairs[i][1]])
        valid_patch_indices.append(i)
    
    

In [210]:
valid_patches = np.array(valid_patches)
valid_patch_indices = np.array(valid_patch_indices)

In [211]:
# with open("Buenos Aires Valid Patches.pkl", "wb") as f:
    # pickle.dump(valid_patches, f)
    
# with open("Buenos Aires Valid Patch Indices.pkl", "wb") as f:
    # pickle.dump(valid_patch_indices, f)